export enum UserRolesEnum {
  OFFICIAL = 'OFFICIAL',
  ADMIN = 'ADMIN',
}

export enum CampaignPurposeEnum {
  MEDICAL_EXPENSES = 'MEDICAL_EXPENSES',
  HUMANITARIAN_AID = 'HUMANITARIAN_AID',
  SOCIAL_JUSTICE_CAUSES = 'SOCIAL_JUSTICE_CAUSES',
  COMMUNITY_PROJECTS = 'COMMUNITY_PROJECTS',
  DISASTER_RELIEF = 'DISASTER_RELIEF',
}

export enum CampaignStatusEnum {
  OPEN = 'OPEN',
  COMPLETED = 'COMPLETED',
}

export enum DonationStatusEnum {
  PENDING = 'PENDING',
  SUCCESSFUL = 'SUCCESSFUL',
  FAILED = 'FAILED',
}

export enum AuthRolesEnum {
  ADMIN = 'ADMIN',
  VERIFIED = 'VERIFIED',
  CAMPAIGN_OWNER = 'CAMPAIGN_OWNER',
  PROFILE_OWNER = 'PROFILE_OWNER',
}
